# Generated by Django 5.0.6 on 2024-06-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_content_post_content_markdown_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content_html',
        ),
    ]
