# Generated by Django 5.0.6 on 2024-06-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revistas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('volume', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=255)),
                ('secao', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=255)),
                ('genero_textual', models.CharField(max_length=255)),
                ('palavra_chave1', models.CharField(max_length=100)),
                ('palavra_chave2', models.CharField(blank=True, max_length=100, null=True)),
                ('palavra_chave3', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo_autor', models.CharField(max_length=50)),
            ],
        ),
    ]
