# Generated by Django 5.0.6 on 2024-06-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paineis', '0002_revistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revistas',
            name='ano',
            field=models.CharField(max_length=50),
        ),
    ]
